- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
      - id: requirements-txt-fixer
      - id: debug-statements
- repo: https://github.com/timothycrosley/isort
  rev: 5.1.4
  hooks:
      - id: isort
        args: ["--profile", "black"]
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
      - id: black
        language_version: python3.8
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
      - id: flake8
        args: ['--ignore=E501']
        exclude: weatherreport/
        additional_dependencies:
            [
                flake8-bugbear==20.1.4,
                flake8-builtins==1.5.3,
                flake8-django==1.1.1,
            ]
